services:
    mysql:
      container_name: mysql
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: root
      ports:
        - "3307:3306"
      volumes:
        - /Users/sthefanopolitino/Documents/Tesis/db/volume:/var/lib/mysql
    # microservicio:
    #     container_name: microservicio
    #     image: sthefanopoli/microservicio_valuewine:dev
    #     environment:
    #         USERDB: root
    #         PASSDB: root
    #         HOSTDB: mysql
    #         PORTHOSTDB: 3306
    #         KEY: qJdkOKZkOPxxeIYgi1l0kAJMlHtVN9oKAjIH0gsQ
    #     ports:
    #       - "5000:5000"
        
